name: Deploy to Hugging Face
on:
  push:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  sync-to-hub:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Push to Hugging Face
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: git push --force https://satyaballa:$HF_TOKEN@huggingface.co/spaces/satyaballa/YT_Summarizer_Pro HEAD:main
